### ISSUE TITLE
Past years' solutions?

### ISSUE THREAD

**Issue by fpsvogel** [ZogStriP/adventofcode#1]
Recently I started doing past years' Advent of Code puzzles (because it's much less stressful than doing new puzzles in December, haha) and to look at alternative solutions after I solve a puzzle, I was using your repo along with [a few others](https://github.com/fpsvogel/advent_of_ruby?tab=readme-ov-file#arb-bootstrap-year-day) that have complete or nearly-complete solutions in Ruby.

Sadly, past years' solutions have disappeared from your repo. Is there any chance you can bring them back, even if it's in a separate repo? I was enjoying learning from them.

**Comment by ZogStriP** [comment]
I had to "hide" them because the repo had inputs which is against AoC's terms.

I need to "clean" all the files to accept input from a .in file instead of the `DATA` section. But didn't have time just yet.

I sent you an invite on my private/old repository which has all the solutions.

**Comment by ZogStriP** [comment]
Good luck catching up 😉

My solutions tend to be somewhat cryptic, but if you have any questions, please do not hesitate 👍

**Comment by fpsvogel** [comment]
Gotcha, that makes sense. Thanks for the invite.

I don't know if I will ever catch up 😂 But it's fun anyway, especially seeing all the different styles of Ruby solutions. I'll let you know if I have questions!
